# Generated by Django 5.2.1 on 2025-05-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='insights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio',
            field=models.FileField(upload_to='audio_files/'),
        ),
    ]
