version: '3.8'

services:
  wallboard:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wallboard_app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - wallboard_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  wallboard_network:
    driver: bridge

# Optional: Add volume for logs
volumes:
  nginx_logs:
    driver: local